modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPL-3.0"
[[mods]]
modId = "tetra_loopback"
version = "1.0.1-6.13"
displayName = "Tetra Loopback"
authors = "NEFOR"
description = '''Tetra Loopback is an addon mod for Tetra, designed to add more content and improve the overall experience. '''
[[dependencies."tetra_loopback"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."tetra_loopback"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."tetra_loopback"]]
modId="tetra"
mandatory=true
versionRange="[6.5.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies."tetra_loopback"]]
modId="mutil"
mandatory=true
versionRange="[6.0,)"
ordering="AFTER"
side="BOTH"
[[dependencies."tetra_loopback"]]
modId ="curios"
mandatory = true
versionRange = "[5.8.1+1.20.1,)"
ordering = "NONE"
side = "BOTH"
